# Generated by Django 4.1.3 on 2022-11-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_id',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
